### ISSUE TITLE
Outputs of the report to be shown also as annotation in workflow run

### ISSUE THREAD

**Issue by maritak0** [joonvena/robotframework-reporter-action#10]
Could the outputs of the report be shown also as annotation in the relevant workflow run? This would help to find the test result summary in case that the testing workflow is started manually or by scheduler.

The place for the info like in the image below, but with the same content as you post to comments at the moment.
![image](https://user-images.githubusercontent.com/100838491/168252757-ed03dbae-2fce-484f-81d9-b249cdf949d6.png)

**Comment by joonvena** [comment]
Hi, yes this is possible and i'm currently working on it. Hopefully have it available during this week :)

**Comment by maritak0** [comment]
You probably have noticed already, but GitHub have [announced](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) on last week a possibility to display markdown in job summary, so actually that might be useful in this case.

**Comment by joonvena** [comment]
Yes i'm working the implementation based on that new addition 🙂

**Comment by joonvena** [comment]
Hello, this is now released and available in joonvena/robotframework-reporter-action@v2.1 🙂. It is enabled by default and can be disabled by setting `summary: 'false'`

**Comment by maritak0** [comment]
Thank you! Now I was able to see the output in workflow run summary 🙂.

![image](https://user-images.githubusercontent.com/100838491/169036272-802d2bbd-decc-4ffb-9332-c9ee8463a9ec.png)

(There is some issue with total amount of tests and pass%, but that was present on earlier release also, so I'll open another issue about that)
