### ISSUE TITLE
Total amount of tests 0 even when there are tests

### ISSUE THREAD

**Issue by maritak0** [joonvena/robotframework-reporter-action#12]
There are tests run, but the total amount shows 0:

![image](https://user-images.githubusercontent.com/100838491/169037118-08426ba3-de24-4a4b-bf60-72e10d2c5eeb.png)

output.xml attached as a reference
[output.zip](https://github.com/joonvena/robotframework-reporter-action/files/8716228/output.zip)

**Comment by joonvena** [comment]
I tested it out with the output.xml you provided and it indeed doesn't output the total or %. This revealed major problem with the action itself as it expects the tests to have flat structure so they are all inside the same folder. When there is folders they create extra suite elements which is expected this wasn't taken into consideration when designing the action. Thanks you for this and i'm going to start implementing feature so it will support multiple suites.

**Comment by joonvena** [comment]
I just released updated v2.1 version with improved parsing. Can you now verify if everything works :slightly_smiling_face:

**Comment by maritak0** [comment]
Thank you! I tested the new version and now it works as expected. The Total  and Pass % is visible and the Passed Tests and Failed tests tables also. 

![image](https://user-images.githubusercontent.com/100838491/169746424-f5a0a669-d462-4547-96eb-fe4fbbb46a09.png)
