### ISSUE TITLE
Unable to read output.xml file when it is located under reports/testsuite/testsuite1 

### ISSUE THREAD

**Issue by satish-dosapati** [joonvena/robotframework-reporter-action#15]
Hi,

I have two different directories under reports like
reports/testsuite/testsuite1/output.xml
reports/testsuite/testsuite2/output.xml

When I try to read these xml files using below code 
      - name: Send reports summery
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: reports/* / *

it is searching for .../reposts/ * / */ output.xml, it is not considering * as sub directory.
I tried with reports/ ** / ** and 'reports/ ** / **' and 'reports/ * / *' all the combinations it is not reading the file under sub directories.
Can you please help me on how to read all output.xlm files from sub directories.

NOTE: I gave spaces after * and / in this query for readability, in real project I didn't give spaces

**Comment by joonvena** [comment]
Hello, this action expects that your reports is combined to single output.xml. Your only options are to execute this action separately for all the paths or then use rebot_cli to combine these reports to one before passing it to the action:

https://robot-framework.readthedocs.io/en/v3.2.2/autodoc/robot.html?highlight=run_cli#robot.rebot.rebot_cli
